openapi: 3.0.3
info:
  title: 7energy API spec
  description: 7energy API spec
  version: 1.0.0
servers:
  - url: 'https://api.seven.gy/v1'
paths:
  /recs:
    get:
      summary: Get all recs
      responses:
        '200':
          description: List of recs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rec'
    post:
      summary: Add a new rec
      responses:
        '405':
          description: Invalid input
    put:
      summary: Update an existing rec
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Rec not found
        '405':
          description: Validation exception
  /recs/{recId}:
    get:
      summary: Get details of a specific rec
      parameters:
        - name: recId
          in: path
          description: uuid of the rec
          required: true
          schema:
            $ref: '#/components/schemas/Rec/properties/uuid'
      responses:
        '200':

components:
  schemas:
    Rec:
      type: object
      required: uuid
      properties:
        uuid:
          type: string
        name:
          type: string